version: "3.9"

services:

  ai-predict:
    build: ./ai/predict
    container_name: ai-predict
    ports:
      - "5101:5101"

  ai-analyze:
    build: ./ai/analyze
    container_name: ai-analyze
    ports:
      - "5002:5002"

  backend:
    build: ./backend
    container_name: stock-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./data:/data
    depends_on:
      - ai-predict
      - ai-analyze
      - mongo

  mongo:
    image: mongo:6
    container_name: stock-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  frontend:
    build: ./frontend
    container_name: stock-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend

volumes:
  mongo_data:
